export type Layout =
  | 'page'
  | 'list'
  | 'stream'
  | 'new-project-page'
  | 'project-settings-basic-page'
  | 'project-settings-members-page'
  | 'project-settings-theme-page'
  | 'project-settings-notifications-page'
  | 'project-settings-page-data-page'
  | 'project-settings-backup-page'
  | 'project-settings-advanced-page'
  | 'project-settings-billing-page'
  | 'settings-profile-page'
  | 'settings-extensions-page'
  | 'settings-delete-account-page';
